#! /bin/bash
# @(#) 
#==========================================================================
# File            : checkList
# Description     : 
#
# Revision History: 
#
#   15 Jan 2010 - Brian Marshall,,,,
#      Initial Version.
#==========================================================================
choice=$(dialog --checklist "Chose OS: " 15 40 5 \
1 Linux off \
2 Solaris on \
3 'HP UX' off \
4 AIX off)

echo "You chose $choice"
