#! /bin/bash
# @(#) A gauge Box example with dialog
#==========================================================================
# File            : gaugeBox
# Description     : 
#
# Revision History: 
#
#   15 Jan 2010 - Brian Marshall,,,,
#      Initial Version.
#==========================================================================
(
c=10
while (( c <= 100 )) 
do
   echo $c
   echo "###"
   echo "$c %"
   echo "###"
   ((c += 5))
   sleep 1
done
) 
# | dialog --title "A Test Gauge With dialog" --gauge "Please wait ...." 10 60 0
