#! /bin/bash
# @(#) 
#==========================================================================
# File            : timeBox
# Description     : 
#
# Revision History: 
#
#   15 Jan 2010 - Brian Marshall,,,,
#      Initial Version.
#==========================================================================
tim=$(dialog --stdout --title "A TimeBox" \
                      --timebox "Set the time:" 0 0 10 13 59)

case $? in
0)
  echo "You have set: $tim"   ;;
1)
  echo "You have pressed Cancel"  ;;
255)
  echo "Box closed"   ;;
esac
