#! /bin/bash
# @(#) Configure Git
#==========================================================================
# File            : gitConfig
# Description     : 
#
# Revision History: 
#
#   23 Sep 2011 - Brian Marshall,,,
#      Initial Version.
#==========================================================================
git config --global user.name "Brian Marshall"
git config --global user.email "brian.marshall@oracle.com"
#--------------------------------------------------------------------------
# Set default so that always all changes are pushed to the repository
#--------------------------------------------------------------------------
git config --global push.default "matching"
#--------------------------------------------------------------------------
# Enable some highlighting 
#--------------------------------------------------------------------------
git config --global color.status auto
git config --global color.branch auto
#--------------------------------------------------------------------------
# Enable proxy for Git
# Use: git config --global --unset http.proxy to revoke proxy settings
#--------------------------------------------------------------------------
git config --global http.proxy www-proxy.us.oracle.com:80

#--------------------------------------------------------------------------
# Query your Git settings 
#--------------------------------------------------------------------------
git config --list
