#! /bin/bash
#==========================================================================
# File            : installSSH 
# Description     :
#
# Revision History:
#
# Initial Version
#==========================================================================
if (( $# != 2 ))
then
   echo "Usage: $0 u p"
   exit 1
fi

if [[ ! -e /tmp/.smmm ]]
then
   mkpasswd -l > /etc/passwd
   mkgroup  -l > /etc/group

   touch /etc/sshd_config
   ssh-keygen -t rsa1 -f /etc/ssh_host_key
   ssh-keygen -t rsa  -f /etc/ssh_host_rsa_key
   ssh-keygen -t dsa  -f /etc/ssh_host_dsa_key

   touch /var/log/lastlog
   touch /tmp/.smmm
fi

cygrunsrv -E sshd 
cygrunsrv -R sshd
cygrunsrv -I sshd -p /usr/sbin/sshd -u $1 -w $2 -a -D -e CYGWIN="ntsec nosmbntsec binmode tty" && cygrunsrv --start sshd

ssh-host-config -y
