#! /bin/bash
# @(#) Create Equinox Directories
#==========================================================================
# File            : ced
# Description     : 
#
# Revision History: 
#
#   17 Jan 2008 - Marshall, Brian P
#      Initial Version.
#==========================================================================
projName=${1:?"Usage: $0 <projectName>"}

mkdir -p $projName/{configuration,plugins,lib}
cat <<EOF >$projName/configuration/config.ini
osgi.bundles=org.eclipse.equinox.common@2:start, org.eclipse.update.configurator@3:start
eclipse.ignoreApp=true
osgi.noShutdown=true
EOF

