#! /bin/bash
#==========================================================================
# File            : mtree
# @(#) mtree v1.0 Visual display of a file tree
#
# Revision History: 
#
#   25 Aug 2001 - Brian P. Marshall
#      Initial Version.
#==========================================================================
#   s!|\([^|]*\)$!\1!g
find ${1:-.} -print | sed '
   {
   1d
   s![^/]*/!       | !g
   s!^ *|!!
   }'
