#! /bin/bash
# @(#) Echo the color associated with azure 
#==========================================================================
# File            : azure
# Description     : 
#
# Revision History: 
#
#   19 Feb 2012 - Brian Marshall,,,
#      Initial Version.
#==========================================================================
echo 46 
