#! /bin/bash
# @(#) Echo the color associated with blue 
#==========================================================================
# File            : blue
# Description     : 
#
# Revision History: 
#
#   19 Feb 2012 - Brian Marshall,,,
#      Initial Version.
#==========================================================================
echo 44 
