#! /bin/bash
# @(#) Echo the color associated with green 
#==========================================================================
# File            : green
# Description     : 
#
# Revision History: 
#
#   19 Feb 2012 - Brian Marshall,,,
#      Initial Version.
#==========================================================================
echo 42 
