#! /bin/bash
# @(#) Echo the color associated with purple 
#==========================================================================
# File            : purple
# Description     : 
#
# Revision History: 
#
#   19 Feb 2012 - Brian Marshall,,,
#      Initial Version.
#==========================================================================
echo 45 
