#! /bin/bash
# @(#) 
#==========================================================================
# File            : zcalendar
# Description     : 
#
# Revision History: 
#
#   15 Jun 2012 - Brian Marshall,,,
#      Initial Version.
#==========================================================================
format=""
while getopts :f: option
do
   case $option in
     \?) echo "Bad switch $OPTARG, ignoring";;
      :) echo "Bad option $OPTARG, ignoring";;
      f) format="--date-format=$OPTARG";;
   esac
done

shift $(( OPTIND - 1 ))

zenity --calendar $format
