#! /bin/bash
# @(#) 
#==========================================================================
# File            : zerror
# Description     : 
#
# Revision History: 
#
#   21 Feb 2012 - Brian Marshall,,,
#      Initial Version.
#==========================================================================
zenity --error --text="$*"
