#! /bin/bash
# @(#) 
#==========================================================================
# File            : fileSelector
# Description     : 
#
# Revision History: 
#
#   10 Nov 2012 - Brian Patrick Marshall,,,
#      Initial Version.
#==========================================================================
FILE=`zenity --file-selection --title="Select a File"`

case $? in
   0) echo $FILE;;
   1) echo "No file selected.";;
  -1) echo "An unexpected error has occurred.";;
esac
