#! /bin/bash
# @(#) 
#==========================================================================
# File            : zinfo
# Description     : 
#
# Revision History: 
#
#   21 Feb 2012 - Brian Marshall,,,
#      Initial Version.
#==========================================================================
zenity --info --text="$*"
