#! /bin/bash
# @(#) 
#==========================================================================
# File            : showPDF
# Description     : 
#
# Revision History: 
#
#   07 Aug 2012 - Brian Patrick Marshall,,,
#      Initial Version.
#==========================================================================
for dir in $(lsd | grep 2)
do   
   cd $dir
   acroread *.pdf
   cd - 
done
