#! /bin/bash
# @(#) 
#==========================================================================
# File            : getA
# Description     : 
#
# Revision History: 
#
#   22 Nov 2004 - marshabp,U-MDNT\marshabp,S-1-5-21-854245398-861567501-725345543-3247
#      Initial Version.
#==========================================================================
grep -i ${1:?Usage: $0 name} ~/.hidden/.addresses | hlp '(.*) ...-....'
