#! /bin/bash
# @(#) 
#==========================================================================
# File            : scpMML
# Description     : 
#
# Revision History: 
#
#   29 Sep 2011 - Brian Marshall,,,
#      Initial Version.
#==========================================================================
scp $* medmerch@
