#! /bin/bash
# @(#) 
#==========================================================================
# File            : tailLastFile
# Description     : 
#
# Revision History: 
#
#   25 Jan 2012 - Brian Marshall,,,
#      Initial Version.
#==========================================================================
pattern=${1:-.}

#--------------------------------------------------------------------------
# Loop until the current directory has an ordinary file.
#--------------------------------------------------------------------------
while :
do
   if (( $( ls -l | grep -v '^d' ) > 0 ))
   then
      #--------------------------------------------------------------------
      # There is a non-directory file
      #--------------------------------------------------------------------
      break
   else
     sleep 1
   fi
done

#--------------------------------------------------------------------------
# Choose the "newest" (ls -ltr => reverse time order long listing) non-dir
#--------------------------------------------------------------------------
lastFile=$(ls -ltr | grep -v '^d' | tail -1)
while :
do
  tail -f $lastFile | grep $pattern
done
