#! /bin/bash
# @(#) Initialze VPN
#==========================================================================
# File            : vpnInit
# Description     : 
#
# Revision History: 
#
#   11 Sep 2011 - Brian Marshall,,,
#      Initial Version.
#==========================================================================
# sudo /etc/init.d/vpnclient_init start
sudo /opt/cisco-vpnclient/bin/vpnclient connect oracle 
