#! /bin/bash
# @(#) 
#==========================================================================
# File            : junk
# Description     : 
#
# Revision History: 
#
#   07 Jul 2012 - Brian Patrick Marshall,,,
#      Initial Version.
#==========================================================================
coproc { cat /tmp/junk;  sleep 2; }
# Try running this without "sleep 2" and see what happens.

while read -u ${COPROC[0]} line    #  ${COPROC[0]} is the
do                                 #+ file descriptor of the coprocess.
  echo "$line" | sed -e 's/line/NOT-ORIGINAL-TEXT/'
done

kill $COPROC_PID                   #  No longer need the coprocess,
                                   #+ so kill its PID.
